project:
  type: website
  output-dir: .
  render:
  - "*.qmd"
  - "!dash/summary.qmd"

website:
  title: "Big Sur SOD Analysis"
  search: true
  navbar:
    left:
      - text: "Project Notes"
        href: ./index.qmd
      - text: "Hypothesis"
        href: ./hypo.qmd
      - text: "Plot/PCA"
        href: ./plot.qmd
      - text: "Living Biomass"
        href: ./biomass.qmd
      - text: "Survival Analysis"
        href: ./survival.qmd
      - text: "CWD"
        href: ./cwd.qmd
      - text: "Cleaning"
        href: ./clean.qmd
      - text: "Data Download"
        href: https://github.com/benparker9/bigsur/tree/master/scripts/data
format:
  html:
    page-layout: full
    code-tools: true
    embed-resources: true
    theme: superhero
    code-fold: true


resources:
  - red.mp4




