project:
  type: website
  output-dir: docs 
  render:
  - "*.qmd"
  - "!dash/summary.qmd"

website:
  title: "Big Sur SOD Analysis"
  search: true
  navbar:
    left:
      - text: "Thesis"
        href: ./index.qmd
      - text: "Data Cleaning/Package Download"
        href: ./clean.qmd

format:
  html:
    page-layout: full
    code-tools: true
    embed-resources: true
    theme: united 
    code-fold: true




