project:
  type: website
  output-dir: .
  render:
  - "*.qmd"
  - "!dash/summary.qmd"

website:
  title: "Big Sur SOD Analysis"
  search: true
  navbar:
    left:
      - text: "Project Notes"
        href: ./index.qmd
      - text: "Data Exploration"
        href: ./plot.qmd
      - text: "Living Biomass"
        href: ./biomass.qmd
      - text: "CWD"
        href: ./cwd.qmd
      - text: "Original Data/R Package"
        href: ./clean.qmd

format:
  html:
    page-layout: full
    code-tools: true
    embed-resources: true
    theme: united 
    code-fold: true




