---
format: 
  html:
    toc: true 
editor: visual
execute:
  warning: false
  message: false
---

### Needed libraries   
```{r}
library(tidyverse)
library(here)
library(readxl)
library(sf)
library(leaflet)
```    

```{r}
#speed up importing data
read_me <- function(path, status){
  read.csv(here("data",status, path))
}
# speed up export to data/clean
export_me <- function(df,path){
  write.csv(df, here("data","clean", path))
}

```


```{r}
bias <- read_me("bias.csv", "clean")  
z_score <- function(df,x){
  df1 <- df |>
    summarize(
      pop_mean <- mean({{x}}, na.rm=TRUE),
      pop_sd <- sd({{x}}, na.rm=TRUE)) |>
        rename(Mean = 1, Sd = 2) 
  df <- df |>
    mutate(ZScore = ({{x}} - df1$Mean)/ df1$Sd)
  return(df)
}
#sd = 2.311 mean=3.21 
# plotted bias histogram to verify Poisson distribution
bias_mod1 <- z_score(bias, TotalTimesInventoried)

# simulate poisson distribution 280 total, mean of 3.2
set.seed(331)
sim <- data.frame(Simulated = rpois(280,3.2)) 
sim_mod1 <- z_score(sim,Simulated)

# simulated zscore dataset is slightly right skewed, project dataset is heavily right skewed
# simulated zscore dataset has no values over ~3 while project dataset has values near 4
# radius is built on times inventoried
# color will be built on z-score
# project dataset, if z-score < -0.5 they get green
# if z-score > 3 they get red
# use of binning 3
bias_mod2 <- bias_mod1 |>
  mutate(Color = case_when(
                           ZScore < -0.5 ~ "Green",
                           ZScore > 2.75 ~ "Red",
                           TRUE ~ "Blue"
                           ))
#export_me(bias_mod2, "q7-map.csv")

# need this for .docx render
bias_hist <- bias_mod1 |>
  select(TotalTimesInventoried, ZScore) |>
  rename(Count = TotalTimesInventoried) |>
  mutate(Dataset = "Tree") 

sim_hist <- sim_mod1 |>
  rename(Count = Simulated) |>
  mutate(Dataset = "Simulated")
comp_hist <- bind_rows(bias_hist,sim_hist)


```


```{r}
map <- bias_mod2

leaflet(map) %>%
  addTiles() %>%
  addProviderTiles(providers$Esri.WorldImagery) %>%
  setView(lng = mean(map$Lon), lat = mean(map$Lat), zoom = 9) %>%
  addCircleMarkers(
    lng = ~Lon,
    lat = ~Lat,
    radius = ~Radius * 1.2,  # scale up for visibility
    label = ~Plot,
    popup = ~paste0(
      "<b>Plot:</b> ", Plot, "<br>",
      "<b>Times Inventoried:</b> ", TotalTimesInventoried, "<br>",
      "<b>Visit Frequency:</b> ", VisitFrequency
    ),
    color = ~Color,
    fillOpacity = 0.7
  ) |>
  addControl(
    html = "<b style='font-size:12px;'>Bias in Sampling Frequency</b>",
    position = "topright"
  ) 
  #|>
    #htmlwidgets::saveWidget("")

```



```{r}
#CePlot 0=has ever had veg cov class <10%; 1= >10%; 2= >25%)

raw_plot <- read_me('raw_plotDB.csv', 'raw') |>
  slice(-1) |>
  select(1,2, 5, 27, 40, 50, 51, 63, 64) |>
  rename(PlotBS = 2,
         ForestType = 3,
         YearsBurned = 4,
         CePlot = 5,
         Trail = 6,
         Owner = 7,
         PlotAspect = 8,
         OverallAspect = 9) |>
  separate_wider_delim(YearsBurned, delim = ",", names_sep = "_", 
                       too_few = "align_start") |>
  pivot_longer(cols = YearsBurned_1:YearsBurned_6, names_to = "Year", 
               values_to = "YearBurned") |>
  mutate(YearBurned = str_trim(YearBurned)) |>
  drop_na(YearBurned)

plot <- read_me('plotDB.csv', 'raw')

plotDB <- left_join(raw_plot, plot, by = c("PlotBS" = "Plot"), relationship = "many-to-many") |>
  separate_wider_delim(YearBurned, delim = " ", names_sep = "_",
                       too_few = "align_start") |>
  pivot_longer(cols = YearBurned_1:YearBurned_2, names_to = "trans", values_to = "YearBurned") |>
  drop_na(YearBurned, BurnScar) |>
  select(!c(Year, trans)) |>
  mutate(YearBurned = case_when(
         YearBurned %in% c("none", "") ~ "0",
         TRUE ~ YearBurned
       )) |>
  mutate(across(c(Plot, ForestType, PlotAspect, OverallAspect, YearBurned), as.numeric)) 

#plot_t <- plotDB |>
#  select(PlotBS, YearBurned, BurnScar) |>
#  distinct() |>
#  filter(BurnScar == "dolan") |>
#  group_by(PlotBS, BurnScar) |>
#  summarize(YearBurnedSecondMax = nth(sort(YearBurned, decreasing = TRUE), 2),
#            YearBurnedMax = max(YearBurned))
#
## time since fire calcs
#recent <- plotDB |>
#  mutate(tFire = case_when(
#                           BurnScar == "dolan" & SampleYear >= 2020 ~ SampleYear - 2020,
#                           BurnScar == "dolan" & SampleYear < 2020 ~ SampleYear - YearBurnedMax,
#                           BurnScar == "dolan_chalk" & SampleYear >= 2020 ~ SampleYear - 2020,
#                           BurnScar == "dolan_chalk" & SampleYear < 2020 & SampleYear > 2008 ~ SampleYear - 2008,
#                          BurnScar == "dolan_chalk" & SampleYear <= 2016 ~ SampleYear - YearBurnedSecondMax,
#                           BurnScar == "sober" & SampleYear > 2016 ~ SampleYear - 2016,
#                           BurnScar == "sober" & SampleYear <= 2016 ~ SampleYear - YearBurned,
#                           BurnScar == "sober_chalk" & SampleYear >= 2016 ~ SampleYear - 2016,
#                           BurnScar == "sober_chalk" & SampleYear < 2016 & SampleYear > 2008 ~ SampleYear - 2008,
#                            BurnScar == "sober_chalk" & SampleYear <= 2008 ~ SampleYear - YearBurned,
#                            BurnScar == "chalk" & SampleYear > 2008 ~ SampleYear - 2008,
#                          BurnScar == "chalk" & SampleYear <= 2008 ~ SampleYear - YearBurned,
#                          BurnScar == "control" ~ SampleYear - YearBurned)) |>
#  filter(tFire <= 0) |>
#  select(PlotBS, BurnScar, SampleYear, YearBurned, tFire) 
#



```

## Principle Component Analysis     

**Objective**   
- Better understand variability within the plot dataset   
- Add groups beyond Plot ID to test as random factors 


**Covariance Matrix**   

```{r}
library(corrr)
make_titles <- function(x){
  # expects a character or factor as an input
  stopifnot(is.character(x) | is.factor(x))
  
  # remove the units at the end of the name
  str_remove(x, pattern = "(g|mm)$") |> 
  # replace all _ with spaces
  str_replace_all(pattern = "_", replacement = " ") |> 
  # remove extra whitespace on left 
  str_trim(side = "both") |> 
  # convert the first letter of each word to upper case
  str_to_title()
}

cor_matrix <- function(df, title) {
  df |>
    select(where(is.numeric)) |>
    correlate(method = "pearson",
            use = "pairwise.complete.obs") |>
    rename(term1 = term) |> 
    pivot_longer(cols = -term1, 
               names_to = "term2", 
               values_to = "correlation") |>
    mutate(
      across(.cols = c(term1, term2), 
           .fns = ~ make_titles(.x)
           )
    ) |> 
    ggplot(mapping = aes(x = term1,
                       y = term2, 
                       fill = correlation)) +
      geom_tile() +
      labs(x = "", 
       y = "", 
       title = paste("Correlation Matrix of:", title), 
       fill = "Correlation"
       ) +
      theme_bw() +
      scale_fill_viridis_c(option = "B")

}

cor_matrix(plotDB, "Plot Factors")

```



```{r}
# only numeric cols, will auto scale, center and return transformed data

pca_me <- function(df) {
  df1 <- df |>
    select(!CePlot) |>
    select(where(is.numeric)) |>
    drop_na() 
  pca <- prcomp(df1, scale. = TRUE, center = TRUE, retx = TRUE)
  
  pca_var <- pca$sdev^2
  propve <- pca_var / sum(pca_var)

  j <- plot(propve, xlab = "Principal Component",
     ylab = "Proportion of Variance Explained",
     ylim = c(0, 1), type = "b", main = "Scree Plot")
  
  return(j)
}


pca_me(plotDB)


```









