---
title: "Big-sur data analysis"
format: html
editor: visual
---

## Table of Contents:

```{r}
library(tidyverse)
library(here)
library(broom)
library(gtsummary)
library(survival)
library(ggsurvfit)


read_me <- function(path){
  read_csv(here("data", path))
}
export_image <- function(img, path){
  ggsave(filename = here("exports", path), plot=img, width=12, height=8)
}


grey_theme <- function() {
  theme(
  plot.title = element_text(
      size = 16,
      family = "Times New Roman",
      face = "italic",
      color = "black", 
      margin = margin(b = 15)
    ),
    # add border 1)
    panel.border = element_rect(colour = "black", fill = NA, linetype = 2),
    # color background 2)
    panel.background = element_rect(fill = "white"),
    # modify grid 3)
    panel.grid.major.x = element_line(colour = "grey", linetype = 3, linewidth = 0.5),
    panel.grid.minor.x = element_blank(),
    panel.grid.major.y =  element_line(colour = "grey", linetype = 3, linewidth = 0.5),
    panel.grid.minor.y = element_blank(),
    # modify text, axis and colour 4) and 5)
    axis.text = element_text(colour = "black", face = "italic", family = "Times New Roman"),
    axis.title = element_text(colour = "black", family = "Times New Roman"),
    axis.ticks = element_line(colour = "black"),
    # legend at the bottom 6)
    legend.position = "bottom"
  )
}

```



### Survival Analysis
### Need to load and transform data into survival tables
  - Create t and set t0 = 2006
```{r}
tree <- read_me("tree_table_FINAL.csv")

tree1 <- tree |>
  filter(Species %in% c("SESE", "LIDE","UMCA")) |> 
  rename(Disease = p_ram.presence,
         Fire = fire_presence) |>
  filter(!is.na(Species)) |>
  mutate(t = SampleYear - 2006,
         Species = case_when(
                             Species == "SESE" ~ "Redwood",
                             Species == "LIDE" ~ "Tanoak",
                             TRUE ~ "Bay laurel")) |>
  select(BS_plot, Species, t,RametFail,Disease,Fire, DBH)

tree1 %>% 
  mutate(status = dplyr::recode(RametFail,"0" = "Censored", "1" = "Death")) %>% 
  tbl_summary(by = status,
              statistic = list(all_continuous() ~ "{mean} ({sd})", 
                              all_categorical() ~ "{n} ({p}%)"),
              type = list(where(is.logical) ~ "categorical"),
              label = list(Disease ~ "Disease status", 
                           DBH ~ "DBH", 
                           t~"t"),
            missing_text = "Missing") %>% 
  modify_caption("**Table 1. Patient Characteristic**")  %>%
  modify_header(label ~ "**Variable**") %>% 
  modify_spanning_header(c("stat_1", "stat_2") ~ "**Survival Status**") %>%
  modify_footnote(all_stat_cols() ~ "Mean (SD) or Frequency (%)") %>%
  bold_labels() %>%
  as_gt()

```

### Weibull model

```{r}
s1 <- survfit2(Surv(t,RametFail) ~ Species, data=tree1)

p1 <- s1 |>
  ggsurvfit() +
  facet_wrap(~strata) +
  add_risktable() +
  theme_classic() +
  labs(title="Kaplan-Meier Survival Function of Big Sur Species", x="Time")

export_image(p1, "surv.png") 




``` 








